# https://rust-lang.github.io/rustfmt/?version=v1.8.0
edition = "2024"
max_width = 120
newline_style = "Unix"
chain_width = 120
fn_call_width = 120
match_block_trailing_comma = true

hard_tabs = true
tab_spaces = 2

# unstable_features = true
# imports_layout = "HorizontalVertical"
# imports_granularity = "Crate"
# format_code_in_doc_comments = true
