name: Testing

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: CI run
        run: node index.js "tests/**/*.liquid" -c | tee /tmp/report.txt
        continue-on-error: true

      - name: Report with reviewdog
        uses: reviewdog/reviewdog@v0.20
        with:
          name: liquid-lint
          reporter: github-pr-review
          fail_on_error: false
          errorformat: "%f:%l:%c: %t%*[a-z]: %m"
          input: /tmp/report.txt
