name: Testing

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: CI run
        run: node index.js "tests/fixtures/**/*.liquid" -c
        continue-on-error: true

      - name: CI with parsing errors
        run: node index.js "tests/fixtures/**/*.liquid" -c -e
        continue-on-error: true

      - name: CI with warnings and parsing errors
        run: node index.js "tests/fixtures/**/*.liquid" -c -e -w
        continue-on-error: true
